# -*- coding: utf-8 -*-
"""Advance Python - Major.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FE24yJ_knVOo2TRFd_KbuAoAQGeihdeL
"""

import pandas as pd
# pandas is aliased as pd
import numpy as np
# numpy is aliased as np
import matplotlib.pyplot as plt
# pyplot is aliased as plt
import seaborn as sns
# seaborn is aliased as sns

import warnings
warnings.simplefilter("ignore")

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/Colab Notebooks/honeyproduction 1998-2021.csv')
df.head()# top 5 rows

df.shape
# Rows = 985 ,& Column = 8

"""# **A. Data Preprocesing**"""

df.isnull().sum()

"""# **B. Check Datatypes**"""

df.dtypes

"""# **C.Checking Duplicate Values**



"""

df.duplicated().sum()



"""###<b>D.Extract all Categorical Columns and Numerical Columns<b>"""

cat_cols = df.select_dtypes(include='object').columns
print(cat_cols)
num_cols = df.select_dtypes(exclude='object').columns
print(num_cols)

s2 = df['State'].value_counts()
print(type(s2)) # Series
s2

s3 = df['year'].value_counts()
s3

"""# **1. How has honey production yield changed from 1998 to 2021 ?**"""

ndf = df[df['year']>=1998]
ndf.head()

plt.figure(figsize=(100,19))
sns.barplot(data=ndf,x='State',y='totalprod',hue='year',ci=None)
plt.xticks(rotation=90)
plt.grid()
plt.show()
plt.savefig('Year Yield Changes (1998-2021).png')

"""# **2. Over Time, What Are The Major Production Trends Across The States ?**"""

sdf = df.groupby(['year','State'])['totalprod'].max().reset_index()
print(type(sdf)) # DataFrame
sdf.head(100)

sns.set_style('darkgrid')
sns.set_context('notebook')
sea = sns.FacetGrid(sdf,col='year',col_wrap=7,height=4,aspect=2.5)
sea.map(sns.scatterplot,'State','totalprod')
plt.xticks(rotation=90)
plt.show()
plt.savefig('OverTime Major Prod.png')

"""## **3.Does The Data Show Any Trends In Terms Of The Number of Honey Producing Colonies and Yield Per Colony Before 2006, Which Was When Concern Over Colony Collapse Disorder Spread Nationwide ?**"""

n2df = df[df['year']<2006] # Before 2006 
n2df.tail()

plt.figure(figsize=(100,10))
sns.barplot(data=n2df,x='yieldpercol',y='numcol',hue='year',ci=None)
plt.grid()
plt.legend(loc='upper left')
plt.show()
plt.savefig('Trends Yield Changes.png')

"""# **4.Are There Any Patterns That Can Be Observed Between Total Honey Production and Value of Production Every Year ?**"""

s3 = df.groupby(['year'])[['totalprod','prodvalue']].sum()
s3

s3.plot(kind='line',marker='o')
plt.xlabel('Year',fontsize=15)
plt.xticks(rotation=360)
plt.legend(['Total Honey Production','Value Of Production'],loc='upper left')
plt.show()
plt.savefig('Pattern Observed.png')

"""# **5.How Has The Value of Production, Which in Some Sense Could Be Tied to Demand, Changed Every Year ?**"""

s4 = df.groupby(['year'])[['stocks','prodvalue']].sum()
s4

s4.plot(kind='bar')
plt.xlabel('Year',fontsize=13,color='indigo')
plt.title('Value Of Production ~ Demand Changed Every Year',fontsize=11,color='indigo')
plt.legend(['Stocks','Value Of Production'],loc='upper left')
plt.show()
plt.savefig('Demand Changed Year Wise.png')

"""# **6.Constructs the related plots using Seaborn and Matplot apply customization and derive insights from the visualization.**"""

s4 = df.groupby(['year'])[['stocks','prodvalue']].sum()
s4

s4.plot(kind='line',marker='*')
plt.title('Year wise Sum of Stocks & Value Of Production ',fontsize=12,color='red')
plt.xlabel('Year',fontsize=15,color='green')
plt.legend(['Stocks','Value Of Production'],loc='upper left')
plt.show()
plt.savefig('Related Visualisation1.png')

plt.figure(figsize=(16,7))
sns.countplot(x= df['State'])
plt.title('State Wise Honey Producer - Vertical Bar Chart',color='red')
plt.xlabel('States',fontsize=13,color='purple')
plt.xticks(rotation=90)
plt.show()
plt.savefig('Related Visualisation2.png')

